# Week 1 
# Intro to working with neural nets in keras

Before running this the first time, you will need to install keras if you haven't done it previously!

The easiest way to do this is to open a terminal/console window and do the following:

First, if you have created a new environment (e.g., called "emi") for this class, activate it. (If you haven't created an environment then skip this step):

`conda activate emi`


In [13]:
# Now do your imports
import numpy as np
from keras.models import Sequential #base keras model
from keras.layers import Dense, Activation #dense = fully connected layer
from tensorflow.keras.optimizers import SGD
import h5py # for saving a trained network

## Part 1: A very, very simple example

Can we train a single, 1-input neuron to learn the function output = 5 * input ? 

In [2]:
#Let's make a training dataset with 3 examples
x_train = np.array([[2], [1], [-3]]) #Input values for each of our 3 training examples
y_train = np.array([10, 5, -15]) #Output values (aka "targets") for each of our 3 training examples

In [3]:
# Create the network using keras
num_neurons = 1
model = Sequential() #the basic keras model class
model.add(Dense(num_neurons, input_dim = 1)) #add a "layer" of 1 neuron, which has 1 input value. This will compute a weighted sum, with no additional activation function.
model.summary() #print out info about this network

Metal device set to: Apple M1 Pro
Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 1)                 2         
                                                                 
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________


2022-04-27 11:54:37.963139: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2022-04-27 11:54:37.963366: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


In [4]:
#Set some training parameters
#use stochastic gradient descent (pretty standard optimisation method) with a learning rate of 0.1 (why not?)
sgd = SGD(learning_rate=0.1) #Note that in previous versions the "learning_rate" parameter was titled "lr" instead

#optimise the mean squared error (i.e., the mean of the squared difference between the model's output and the training target, for each training example)
#    This is a fairly standard choice when predicting a real value (as opposed to a binary class of 0 or 1)
model.compile(loss='mean_squared_error', optimizer=sgd)

In [5]:
# Run the current model on each of the training examples (i.e., using the inputs to calculate the neuron output)
model.predict(x_train) #outputs garbage as it's not trained yet: It's computing output = w1 * input + w0 using random values of w0 and w1

2022-04-27 11:54:46.798346: W tensorflow/core/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz
2022-04-27 11:54:46.830581: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


array([[-2.4139264],
       [-1.2069632],
       [ 3.6208897]], dtype=float32)

In [6]:
#train the model!
model.fit(x_train, y_train, epochs=10)

Epoch 1/10
1/1 [==============================] - 0s 174ms/step - loss: 179.7898
Epoch 2/10
1/1 [==============================] - 0s 5ms/step - loss: 0.7991
Epoch 3/10
1/1 [==============================] - 0s 6ms/step - loss: 0.0036
Epoch 4/10
1/1 [==============================] - 0s 5ms/step - loss: 1.5787e-05
Epoch 5/10
1/1 [==============================] - 0s 6ms/step - loss: 7.0200e-08
Epoch 6/10
1/1 [==============================] - 0s 5ms/step - loss: 3.1446e-10
Epoch 7/10
1/1 [==============================] - 0s 5ms/step - loss: 1.5916e-12
Epoch 8/10
1/1 [==============================] - 0s 5ms/step - loss: 0.0000e+00
Epoch 9/10
1/1 [==============================] - 0s 5ms/step - loss: 0.0000e+00
Epoch 10/10
1/1 [==============================] - 0s 5ms/step - loss: 0.0000e+00


2022-04-27 11:54:50.145499: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


In [7]:
#Now run it:
model.predict(x_train) #Does it produce values similar to y_train? It should...

array([[ 10.],
       [  5.],
       [-15.]], dtype=float32)

In [8]:
#we can (and should) run it on some new data, too... 
new_values = np.array([[-10], [0], [5]]) # 3 new "data points"

#Does it output 5 * x for each new value x ?
model.predict(new_values) #be careful to read this using scientific notation ;)

array([[-5.0000000e+01],
       [-1.2901104e-07],
       [ 2.5000000e+01]], dtype=float32)

In [9]:
#Let's look at the model's weights! We'll see (1) the weight for the input, and (2) the weight for the bias
model.get_weights()

[array([[5.]], dtype=float32), array([-1.2901104e-07], dtype=float32)]

In [10]:
# Perhaps try with a new dataset in which our training example output (target) values are np.array([11, 6, -14])?
y_train_new = np.array([11, 6, -14])
model = Sequential() #the basic model class
model.add(Dense(num_neurons, input_dim = 1)) #add a "layer" of 1 neuron, which has 1 input value. This will compute a weighted sum, with no additional activation function.
model.summary()
sgd = SGD(lr=0.1) 
model.compile(loss='mean_squared_error', optimizer=sgd)
model.fit(x_train, y_train_new, epochs=15)

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_1 (Dense)             (None, 1)                 2         
                                                                 
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________
Epoch 1/15
1/1 [==============================] - 0s 145ms/step - loss: 122.5262
Epoch 2/15
1/1 [==============================] - 0s 5ms/step - loss: 1.1801
Epoch 3/15
1/1 [==============================] - 0s 5ms/step - loss: 0.4120
Epoch 4/15
1/1 [==============================] - ETA: 0s - loss: 0.2622

/Users/terence/miniforge3/envs/3mi/lib/python3.8/site-packages/keras/optimizer_v2/gradient_descent.py:102: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(SGD, self).__init__(name, **kwargs)
2022-04-27 11:55:16.828977: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


1/1 [==============================] - 0s 5ms/step - loss: 0.2622
Epoch 5/15
1/1 [==============================] - 0s 5ms/step - loss: 0.1678
Epoch 6/15
1/1 [==============================] - 0s 5ms/step - loss: 0.1074
Epoch 7/15
1/1 [==============================] - 0s 6ms/step - loss: 0.0687
Epoch 8/15
1/1 [==============================] - 0s 5ms/step - loss: 0.0440
Epoch 9/15
1/1 [==============================] - 0s 5ms/step - loss: 0.0281
Epoch 10/15
1/1 [==============================] - 0s 5ms/step - loss: 0.0180
Epoch 11/15
1/1 [==============================] - 0s 5ms/step - loss: 0.0115
Epoch 12/15
1/1 [==============================] - 0s 5ms/step - loss: 0.0074
Epoch 13/15
1/1 [==============================] - 0s 5ms/step - loss: 0.0047
Epoch 14/15
1/1 [==============================] - 0s 5ms/step - loss: 0.0030
Epoch 15/15
1/1 [==============================] - 0s 5ms/step - loss: 0.0019


In [11]:
model.get_weights() #Notice weight is 5 and bias is now 1 (approximately), encoding the function output = input * 5 + 1

[array([[5.]], dtype=float32), array([0.9648157], dtype=float32)]

In [12]:
import tensorflow as tf
print("Num GPUs Available: ", len(tf.config.list_physical_devices('GPU')))

Num GPUs Available:  1
